apiVersion: batch/v1
kind: CronJob
metadata:
  name: image-pruner
  namespace: test
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
      labels:
        created-by: image-pruner
    spec:
      backoffLimit: 0
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity: {}
          containers:
          - args:
            - -c
            - |
              set -eu
              "$@" && exit
              for i in 1 2 3 4 5; do
                echo "attempt #$i has failed (exit code $?), going to make another attempt..." >&2
                sleep $(($i * 30))
                "$@" && break  # this is the last command of the script, so its last failure will be exit code of the script
              done
            - arg0
            - oc
            - adm
            - prune
            - images
            - --confirm=true
            - --certificate-authority=/var/run/configmaps/serviceca/service-ca.crt
            - --keep-tag-revisions=3
            - --keep-younger-than=60m
            - --ignore-invalid-refs=true
            - --loglevel=1
            - --prune-registry=true
            - --registry-url=https://image-registry.openshift-image-registry.svc:5000
            command:
            - /bin/sh
            image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:533ac47e89e1bcf15a78df47260558b022cd41ce89cb353d72dd5ec315823027
            imagePullPolicy: IfNotPresent
            name: image-pruner
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: FallbackToLogsOnError
            volumeMounts:
            - mountPath: /var/run/configmaps/serviceca
              name: serviceca
              readOnly: true
          dnsPolicy: ClusterFirst
          priorityClassName: system-cluster-critical
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: pruner
          serviceAccountName: pruner
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: serviceca
            name: serviceca
  schedule: 0 0 * * *
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 3
  suspend: false
